config/routes.rb
Rails.application.routes.draw do
 
  
 

 
  constraints RoleRouteConstraint.new { |current_user |   current_user.id != nil} do
    root to: 'users#show'
    resources :organizations do 
    resources :teams 
  end
get '/accept_invitations/:id', to: 'accept_invitations#accepted'
  resources :teams do
     resources :teaminvites
   end
  #get '/accept_invitations/:id', to: 'accept_invitations#accepted', as: 'accepted'
   resources :learningstyle_steps
     delete '/logout',  to: 'sessions#destroy'
  get '/logout',  to: 'sessions#destroy'
  resources :users, only: [:edit, :update, :index] do
   resources :organizations
   resources :learningstyles
 end

  end
  
  get 'accepts/show'
resources :accepts
get '/accept_invitations/:id', to: 'accept_invitations#accepted'
  resources :users, only: [:new, :create, :index, :destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :invitations

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'


   root to: 'sessions#new'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :learningstyles, :dependent => :destroy
  has_many :organizations, :dependent => :destroy
  has_many :teaminvites, :dependent => :destroy
   #has_many :teams, :through => :organizations
  attr_accessor :remember_token, :activation_token
  before_save   :downcase_email
  before_create :create_activation_digest
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }


  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end
  
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def password_reset_expired?
    reset_sent_at < 1.hour.ago
  end
  


  private

  def downcase_email
    self.email = email.downcase if email
  end

  def create_activation_digest
    self.activation_token  = User.new_token
    self.activation_digest = User.digest(activation_token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [ :edit, :update, :destroy, :invitation_token]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    respond_to do | format |
      format.html
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = current_user
    @learningstyles = @user.learningstyles.find_by_user_id(@user.id)
    if @learningstyles
      if @learningstyles.completed_no == 80
      @name = Daru::Vector.new [@user.name]
      @activist = Daru::Vector.new [@learningstyles.activisttotal]
      @reflector = Daru::Vector.new [@learningstyles.reflectortotal]
      @theorist = Daru::Vector.new [@learningstyles.theoristtotal]
      @pragmatist = Daru::Vector.new [@learningstyles.pragmatisttotal]
       @organizations = @user.organizations
        @teams = User.joins(organizations: [teams: :teaminvites]).select('teams.team_name as team_name,teams.id as team_id, organizations.org_name as org_name, organizations.id as organization_id, teaminvites.admin').where("teaminvites.user_id = ? AND teaminvites.accepted = ?", current_user.id, 'true').group('teaminvites.id, teams.id, organizations.id')
        else
        redirect_to edit_user_learningstyle_path(@user.id, @user.learningstyles.find_by_user_id(@user.id).id)
      end
    else
      redirect_to new_user_learningstyle_path(@user.id)
    end
end

  # GET /users/new
  def new
    @user = User.new
   # @user.email = @user.invitation.recipient_email if @user.invitation
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json

  def create
    @user = User.new(user_params)
    if @user.save
       #@user.send_activation_email
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url, notice: 'User was successfully created.' 
    else
      render :action => 'new.html.erb'
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to root_url, notice: 'User was successfully updated.' }
        format.json { render :edit, status: :ok, location: @user }
      else
        format.html { render :action =>  'edit.html.erb' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |form| %>


          <%= form.input :name%>
         <span class="spin"></span><br>

          <%= form.input :email %>
          <span class="spin"></span>
   

         <%= form.input :password %>
         <span class="spin"></span>


         <%= form.input :password_confirmation %>
         <span class="spin"></span>


      <div class="button">
         <button><span>NEXT</span></button>
      </div>
      </div>
<% end %>

app/views/users/edit.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
  <%= javascript_include_tag 'application' %>
</head>
<body>

<div class="materialContainer">
    <div class="box" style="background-color: #78c2ad;">

      <div class="title" style="background-color: #1111">UPDATE PROFILE</div>
      <%= simple_form_for(@user) do |form| %>

          <div class="input1">
          <%= form.input :name, :label => 'Name'%>
         <span class="spin"></span><br>
         </div>

         <div class="input1">
          <%= form.input :email, :label => 'Email' %>
          <span class="spin"></span>
          </div>
          <div class="input1">
         <%= form.input :password, :label => 'Password' %>
         <span class="spin"></span>
       </div>

       <div class="input1">
         <%= form.input :password_confirmation, :label => 'Retype password' %>
         <span class="spin"></span>
       </div>


      <div class="button">
         <button><span>NEXT</span></button>
      </div>
      <% end %>
      </div>

</div>

</body>
</html>

app/views/users/index.html.erb
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!DOCTYPE html>
<html style="height: 100%">
   <head>
       <meta charset="utf-8">
   </head>
   <body style="height: 100%; margin: 0">
       <div id="container" style="height: 500px"></div>
       <script type="text/javascript" src="http://echarts.baidu.com/gallery/vendors/echarts/echarts.min.js"></script>
       <script type="text/javascript" src="http://echarts.baidu.com/gallery/vendors/echarts-gl/echarts-gl.min.js"></script>
       <script type="text/javascript" src="http://echarts.baidu.com/gallery/vendors/echarts-stat/ecStat.min.js"></script>
       <script type="text/javascript" src="http://echarts.baidu.com/gallery/vendors/echarts/extension/dataTool.min.js"></script>
       <script type="text/javascript" src="http://echarts.baidu.com/gallery/vendors/echarts/map/js/china.js"></script>
       <script type="text/javascript" src="http://echarts.baidu.com/gallery/vendors/echarts/map/js/world.js"></script>
       <script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=ZUONbpqGBsYGXNIYHicvbAbM"></script>
       <script type="text/javascript" src="http://echarts.baidu.com/gallery/vendors/echarts/extension/bmap.min.js"></script>
       <script type="text/javascript" src="http://echarts.baidu.com/gallery/vendors/simplex.js"></script>
       <script type="text/javascript">
var dom = document.getElementById("container");
var myChart = echarts.init(dom);
var app = {};
option = null;
option = {
    title: {
        text: '基础雷达图'
    },
    tooltip: {},
    legend: {
        data: ['DINESH', 'VONGINESH']
    },
    radar: {
        // shape: 'circle',
        name: {
            textStyle: {
                color: '#fff',
                backgroundColor: '#999',
                borderRadius: 3,
                padding: [3, 5]
           }
        },
        indicator: [
           { name: 'ACTIVITIST', max: 20},
           { name: 'REFLECTOR', max: 20},
           { name: 'THEROIST', max: 20},
           { name: 'PRAGMATIST', max: 20},
           
        ]
    },
    series: [{
        name: '预算 vs 开销（Budget vs spending）',
        type: 'radar',
        // areaStyle: {normal: {}},
        data : [
            {
                value : [4, 10, 2, 3],
                name : 'DINESH'
            },
             {
                value : [5, 14, 2, 3],
                name : 'VONGINESH'
            },
        ]
    }]
};;
if (option && typeof option === "object") {
    myChart.setOption(option, true);
}
       </script>
   </body>
</html>

app/views/users/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
  <%= javascript_include_tag 'application' %>
  <style type="text/css">
    .main-banner {
background-image: url(https://i.imgur.com/TWRdTJh.png);
background-size:cover;
background-position: center center;
min-height:600px;
width:100%
}
  </style>
</head>
<body>
  <div id="home">
 <section id="home-section" class="main-banner">
        <div class="bg-gradient">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <!--Banner Left-Text-->
                        <div class="banner-text">
                            <h1 class="big-text">Learning Styles Questionaire</h1>
                            <p class="content">This questionnaire is designed to find out your preferred learning styles(s). Over the years you have have probably developed learning 'habits' that help you benefit more from some experiences than from others. Since you are probably unaware of this, this questionnaire will help you pinpoint your learning preferences so that you are in a better position to select learning experiences that suit your style.</p>
                      
                        </div>
                    </div>
                    <div class="col-md-5 col-sm-6 col-xs-12 pull-right">
                      <!--Login Div-->
                       <div class="materialContainer1">
                        <div class="box" style="background-color: #78c2ad">
      <h4 class="row" style="background-color: #1111">
      <%= link_to 'REGISTER',new_user_path, class: "col-md-6 col-xs-6 col-sm-6 btn-primary active" %> <%= link_to 'LOGIN',root_path, class: "col-md-6 col-xs-6 col-sm-6 btn-primary" %>
      </h4>
       <%= simple_form_for(@user) do |form| %>

        <div class="input1">
          <%= form.input :name, :label => 'Name'%>
         <span class="spin"></span><br>
       </div>

         <div class="input1">
          <%= form.input :email, :label => 'Email' %>
          <span class="spin"></span>
        </div>
   
         <div class="input1">
         <%= form.input :password, :label => 'Password' %>
         <span class="spin"></span>
       </div>

         <div class="input1">
         <%= form.input :password_confirmation, :label => 'Retype password' %>
         <span class="spin"></span>
       </div>


      <div class="button">
         <button><span>NEXT</span></button>
      </div>
      </div>
<% end %>

</div>
</div>
</div>
    
    </section>

   
</div>

  <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>

</body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>

<div class="row">
<div class="col-md-6">
   <br> 
  <h4 class='text-center'>Learning Styles Questionnaire - Scoring</h4>
   <br> 
  <h5 class='text-center'><%= link_to '(What are you?)', user_learningstyles_path(current_user.id) %></h5>
        <p><strong>Activisttotal</strong> <%= @learningstyles.actstatus %></p>
         <p><strong>Reflectortotal</strong> <%= @learningstyles.refstatus %></p>
        <p><strong>Theorist</strong> <%= @learningstyles.theostatus %></p>
        <p><strong>Pragmatist</strong> <%= @learningstyles.pragstatus %></p> 
        <br> 
        <br> 
        <br> 

</div>
<dov class="col-md-6">
   <br> 
  <h4 class='text-center'>Learning Styles Questionnaire - Scoring</h4>
<div id="container" style="height:100%; width:100%; margin: 0;"></div>
</dov>
<% if @organizations.to_a.count >= 1%>
<div class="col-md-6">
  

<table class="table">
  <h4 class="text-center"><%= link_to 'Organizations', user_organizations_path(current_user.id)%>(<%= @organizations.count%>)</h4>
  <thead>
    <tr>
      <th> </th>
    </tr>
  </thead>

  <tbody>
    <% @organizations.each do |organization| %>
      <tr>
        <td><%= organization.org_name %></td>
        <td><%= link_to 'Teams', organization_teams_path(organization) %>

        </td>
        <td><%= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_user_organization_path(organization.user_id, organization.id) %></td>
        <td><%= link_to '<i class="fa fa-trash-alt"></i>'.html_safe, [organization.user,organization], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<% end %>

<% if @teams.to_a.count >= 1%>

<div class="col-md-6">
  <h4 class="text-center">Teams(<%= @teams.to_a.count %>)</h4>
<table class="table">
  <thead>
    <tr>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @teams.each do |team| %>
      <tr>
        <td><%= team.org_name %>/<%= link_to team.team_name, organization_team_path(team.organization_id, team.team_id) %></td>
        <td><% if team.admin? %> 
            maintaner
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<% end %>

</div>

<script type="text/javascript">
var dom = document.getElementById("container");
var myChart = echarts.init(dom);
var app = {};
option = true;
option = {
    tooltip: {
      trigger: 'axis'
    },
    xAxis: [{
      name: 'Reflector',
      min: -20,
      splitNumber: 10,
      max:20
    },
    {
      name: 'Pragmatist',
      nameLocation: 'start', 
    }],
    yAxis: [{
      name: 'Activist',
      min: -20,
      splitNumber: 10,
      max:20
    },
    {
      name: 'Theorist',
      nameLocation: 'start',
    }
    ],
    series: [{
        data: [
              [0, <%= raw @activist[0].to_i %>],
              [<%= raw @reflector[0].to_i %>, 0],
              [0, -<%= raw @theorist[0].to_i %>],
              [-<%= raw @pragmatist[0].to_i %>, 0],
              [0, <%= raw @activist[0].to_i %>]
              ],
        type: 'line',
    }]
};
;
if (option && typeof option === "object") {
    myChart.setOption(option, true);
}
</script>

</body>
</html>