config/routes.rb
Rails.application.routes.draw do
 
  
 

 
  constraints RoleRouteConstraint.new { |current_user |   current_user.id != nil} do
    root to: 'users#show'
    resources :organizations do 
    resources :teams 
  end
get '/accept_invitations/:id', to: 'accept_invitations#accepted'
  resources :teams do
     resources :teaminvites
   end
  #get '/accept_invitations/:id', to: 'accept_invitations#accepted', as: 'accepted'
   resources :learningstyle_steps
     delete '/logout',  to: 'sessions#destroy'
  get '/logout',  to: 'sessions#destroy'
  resources :users, only: [:edit, :update, :index] do
   resources :organizations
   resources :learningstyles
 end

  end
  
  get 'accepts/show'
resources :accepts
get '/accept_invitations/:id', to: 'accept_invitations#accepted'
  resources :users, only: [:new, :create, :index, :destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :invitations

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'


   root to: 'sessions#new'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  belongs_to :sender, :class_name => 'User'
  has_one :recipient, :class_name => 'User'
  has_many :teams, through: :invitations
  
  validates_presence_of :recipient_email
  validate :recipient_is_not_registered
 
  
  before_create :generate_token
  
private
  
  def recipient_is_not_registered
    errors.add :recipient_email, 'is already registered' if User.find_by_email(recipient_email)
  end
  
  
  def generate_token
    self.token = Digest::SHA1.hexdigest([Time.now, rand].join)
  end
  
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController

  # GET /invitations
  # GET /invitations.json
  def index
    @invitations = Invitation.all
  end

  # GET /invitations/1
  # GET /invitations/1.json
  def show
  end

  # GET /invitations/new
  def new
    @invitation = Invitation.new
  end

  # GET /invitations/1/edit
  def edit
  end

 def create
    @invitation = Invitation.new(invitation_params)
    @invitation.sender = current_user
    if @invitation.save
      if logged_in?
        InvMailer.invitation(@invitation, url_for(@invitation.token)).deliver_now
        flash[:success] = "Thank you, invitation sent."
        redirect_to users_url
      else
        flash[:success] = "Thank you, invitation to join team sent."
        redirect_to teams_url
      end
    else
      render 'new'
    end
  end

  # PATCH/PUT /invitations/1
  # PATCH/PUT /invitations/1.json
  def update
    respond_to do |format|
      if @invitation.update(invitation_params)
        format.html { redirect_to @invitation, notice: 'Invitation was successfully updated.' }
        format.json { render :show, status: :ok, location: @invitation }
      else
        format.html { render :edit }
        format.json { render json: @invitation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invitations/1
  # DELETE /invitations/1.json
  def destroy
    @invitation.destroy
    respond_to do |format|
      format.html { redirect_to invitations_url, notice: 'Invitation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invitation
      @invitation = Invitation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invitation_params
      params.require(:invitation).permit(:sender_id, :recipient_email, :token, :sent_at, :email)
    end
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/invitations/_form.html.erb
<%= form_for @invitation do |form| %>
  <% if invitation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invitation.errors.count, "error") %> prohibited this invitation from being saved:</h2>

      <ul>
      <% invitation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :sender_id %>
    <%= form.number_field :sender_id, id: :invitation_sender_id %>
  </div>

  <div class="field">
    <%= form.label :recipient_email %>
    <%= form.text_field :recipient_email, id: :invitation_recipient_email %>
  </div>

  <div class="field">
    <%= form.label :token %>
    <%= form.text_field :token, id: :invitation_token %>
  </div>

  <div class="field">
    <%= form.label :sent_at %>
    <%= form.datetime_select :sent_at, id: :invitation_sent_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/invitations/edit.html.erb
<h1>Editing Invitation</h1>

<%= render 'form', invitation: @invitation %>

<%= link_to 'Show', @invitation %> |
<%= link_to 'Back', invitations_path %>

app/views/invitations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Invitations</h1>

<table>
  <thead>
    <tr>
      <th>Sender</th>
      <th>Recipient email</th>
      <th>Token</th>
      <th>Sent at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invitations.each do |invitation| %>
      <tr>
        <td><%= invitation.sender_id %></td>
        <td><%= invitation.recipient_email %></td>
        <td><%= invitation.token %></td>
        <td><%= invitation.sent_at %></td>
        <td><%= link_to 'Show', invitation %></td>
        <td><%= link_to 'Edit', edit_invitation_path(invitation) %></td>
        <td><%= link_to 'Destroy', invitation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invitation', new_invitation_path %>

app/views/invitations/new.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<div class="materialContainer">
    <div class="box" style="background-color: #78c2ad">
<h1>New Invitation</h1>

<%= simple_form_for(@invitation) do |form| %>
	<%= form.input :recipient_email %>
	<span class="spin"></span><br>
	
	<div class="button">
         <button><span>Invite!</span></button>
    </div>
</div>
<% end %>

</div>
</div>
</body>
</html>

app/views/invitations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sender:</strong>
  <%= @invitation.sender_id %>
</p>

<p>
  <strong>Recipient email:</strong>
  <%= @invitation.recipient_email %>
</p>

<p>
  <strong>Token:</strong>
  <%= @invitation.token %>
</p>

<p>
  <strong>Sent at:</strong>
  <%= @invitation.sent_at %>
</p>

<%= link_to 'Edit', edit_invitation_path(@invitation) %> |
<%= link_to 'Back', invitations_path %>