config/routes.rb
Rails.application.routes.draw do
 
  
 

 
  constraints RoleRouteConstraint.new { |current_user |   current_user.id != nil} do
    root to: 'users#show'
    resources :organizations do 
    resources :teams 
  end
get '/accept_invitations/:id', to: 'accept_invitations#accepted'
  resources :teams do
     resources :teaminvites
   end
  #get '/accept_invitations/:id', to: 'accept_invitations#accepted', as: 'accepted'
   resources :learningstyle_steps
     delete '/logout',  to: 'sessions#destroy'
  get '/logout',  to: 'sessions#destroy'
  resources :users, only: [:edit, :update, :index] do
   resources :organizations
   resources :learningstyles
 end

  end
  
  get 'accepts/show'
resources :accepts
get '/accept_invitations/:id', to: 'accept_invitations#accepted'
  resources :users, only: [:new, :create, :index, :destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :invitations

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'


   root to: 'sessions#new'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/organization.rb
class Organization < ApplicationRecord
  belongs_to :user
  has_many :teams, :dependent => :destroy
  validates :org_name, presence: true
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  # GET /organizations
  # GET /organizations.json
  def index
    @user = User.find(params[:user_id])
    @organizations = @user.organizations
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
  end

  # GET /organizations/new
  def new
    @user = current_user
    @organization = @user.organizations.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @user = current_user
    @organization = @user.organizations.create(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to root_path, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to root_path, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @user = User.find(params[:user_id])
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @user = User.find(params[:user_id])
      @organization = @user.organizations.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params.require(:organization).permit(:org_name, :user_id)
    end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= simple_form_for([@organization.user, @organization]) do |form| %>
			<div class="input1">
          <%= form.input :org_name, :label => 'organization name'%>
         <span class="spin"></span><br>
         </div>
      <div class="button">
         <button><span>NEXT</span></button>
      </div>
<% end %>

app/views/organizations/edit.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<div class="materialContainer">
    <div class="box" style="background-color: #78c2ad">
<h1>EditOrganization</h1>


<%= render 'form', organization: @organization %>

</div>
</div>
</body>
</html>

app/views/organizations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Organizations</h1>

<table>
  <thead>
    <tr>
      <th>Org name</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @organizations.each do |organization| %>
      <tr>
        <td><%= organization.org_name %></td>
        <td><%= organization.user_id %></td>
        <td><%= link_to 'Show', user_organization_path(organization.user_id, organization.id) %></td>
        <td><%= link_to 'Edit', edit_user_organization_path(organization.user_id, organization.id) %></td>
        <td><%= link_to 'Destroy', (organization.user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organization', new_user_organization_path %>

app/views/organizations/new.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<%= javascript_include_tag 'application' %>
</head>
<body>
<div class="materialContainer1">
    <div class="box" style="background-color: #78c2ad">
<h1>Organization</h1>


<%= render 'form', organization: @organization %>

</div>
</div>
</body>
</html>

app/views/organizations/show.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Team name</th>
      <th>Organization</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @organization.teams.each do |team| %>
      <tr>
        <td><%= team.team_name %></td>
        <td><%= team.organization %></td>
        <td><%= form_for Invitation.new do |form|  %>
            <%= form.text_field :recipient_email, id: :invitation_recipient_email %>
            <%= form.submit 'Invite!' %>
            <% end %>
        </td>
        <td><%= link_to 'Show', team %></td>
        <td><%= link_to 'Edit', edit_team_path(team) %></td>
        <td><%= link_to 'Destroy', team, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>