config/routes.rb
Rails.application.routes.draw do
 
  
 

 
  constraints RoleRouteConstraint.new { |current_user |   current_user.id != nil} do
    root to: 'users#show'
    resources :organizations do 
    resources :teams 
  end
get '/accept_invitations/:id', to: 'accept_invitations#accepted'
  resources :teams do
     resources :teaminvites
   end
  #get '/accept_invitations/:id', to: 'accept_invitations#accepted', as: 'accepted'
   resources :learningstyle_steps
     delete '/logout',  to: 'sessions#destroy'
  get '/logout',  to: 'sessions#destroy'
  resources :users, only: [:edit, :update, :index] do
   resources :organizations
   resources :learningstyles
 end

  end
  
  get 'accepts/show'
resources :accepts
get '/accept_invitations/:id', to: 'accept_invitations#accepted'
  resources :users, only: [:new, :create, :index, :destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :invitations

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'


   root to: 'sessions#new'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<hr class="my-4">
<footer class="footer">
  <nav>
    <p class="nav-item">
      <small>
      &copy Zyelabs
      </small>
    </p>
    
    <ul class="navbar navbar-bottom">
      <li class="nav-item"><%= link_to "Home", root_path,class: "nav-link" %></li>

      <li class="nav-item"><%= link_to "Questionnaire", new_user_learningstyle_url(current_user.id),class: "nav-link" %></li></li>
      <li class="nav-item"><%= current_user.name %></li>
      <li class="nav-item"></li>
    </ul>
    
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
    <div class="bs-example">
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <%= link_to "Learning Style",root_path ,class: "navbar-brand" %>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
            

        <div class="collapse navbar-collapse" id="navbarColor02">
            <ul class="navbar-nav ml-auto">  
              <li class="nav-item"><%= link_to '<i class="fas fa-home"></i> Home'.html_safe, root_path,class: "nav-link" %></li>
              <li class="nav-item"><%= link_to '<i class="fas fa-plus"></i> New organization'.html_safe, new_user_organization_path(current_user.id),class: "nav-link" %></li>
              <li class="nav-item"><%= link_to 'Questionnaire <i class="fas fa-question"></i>'.html_safe, new_user_learningstyle_url(current_user.id),class: "nav-link" %></li>
              <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><span class="user-name">Logged as <%= current_user.name %></span> </a>
              <div class="dropdown-menu" x-placement="bottom-start">
                <%= link_to '<i class="fa fa-user"></i> Profile'.html_safe,"",class: "dropdown-item"%>
                <%= link_to '<i class="fa fa-cog"></i> Settings'.html_safe, edit_user_path(current_user.id),class: "dropdown-item"%>
                <div class="dropdown-divider"></div>
                <%= link_to  '<i class="fas fa-sign-out-alt"></i> Sign out'.html_safe, logout_path,class: "dropdown-item" %>
              </div>
            </li>
            </ul>
    </nav>
  </div>   
     <%# if (controller.controller_name == "users" && controller.action_name == "new") || (controller.controller_name == "users" && controller.action_name == "index") %>
 
   <%# else %> 

  <div class="container"> 
      <%# end %>

app/views/layouts/_notifications.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    $(document).ready(function () {
      toastr.options = {
        "closeButton": false,
        "debug": true,
        "newestOnTop": false,
        "progressBar": false,
        "positionClass": "toast-top-right",
        "preventDuplicates": false,
        "onclick": null,
        "showDuration": "300",
        "hideDuration": "500",
        "timeOut": "3000",
        "extendedTimeOut": "500",
        "showEasing": "swing",
        "hideEasing": "linear",
        "showMethod": "fadeIn",
        "hideMethod": "fadeOut"
      }
      <% flash.each do |f| %>
      <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'success') %>
      toastr['<%= type %>']('<%= f[1] %>');
      <% end %>
    });
  </script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LearningStylesQuestionnare</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
     <%= stylesheet_link_tag 'custom.min.css' %>
     <%= javascript_include_tag 'index.js' %>
     <%= stylesheet_link_tag 'toastr.css' %>
     <%= stylesheet_link_tag 'login.css' %>
     <%= javascript_include_tag 'echarts.js' %>
     <%= javascript_include_tag 'jquery.min.js' %>
     <%= stylesheet_link_tag 'style.css' %>
     <%= stylesheet_link_tag 'bootstrap.css' %>
     

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
<link rel="stylesheet" href="https://bootswatch.com/4/minty/bootstrap.css">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'layouts/notifications' %>

<% if logged_in? %>
<%= render 'layouts/header' %>
<% end %>
 <div class="container"><%= yield %><br></div>
  </body>
</html>




  
  